FROM nvidia/cuda:9.0-devel-ubuntu16.04 AS gpubase

# TensorFlow version is tightly coupled to CUDA and cuDNN so it should be selected carefully
ENV PYTORCH_VERSION=0.4.1
ENV CUDNN_VERSION=7.3.1.20-1+cuda9.0
ENV NCCL_VERSION=2.3.5-2+cuda9.0

RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        curl \
        nano \
        wget \
        unzip \
        ca-certificates \
        libcudnn7=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
		libpng-dev \
		jq \
        locales \
        graphviz
		

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

COPY Docker/environment.yml .

ENV ENV_NAME=py3.6
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda env create -q --name $ENV_NAME -f environment.yml && \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/envs/$ENV_NAME/bin:/opt/conda/bin:$PATH


FROM gpubase AS control

COPY Docker/control_environment.yml .
RUN conda env update -f control_environment.yml

# Install Azure CLI
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ xenial main" | \
    tee /etc/apt/sources.list.d/azure-cli.list && \
    curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    azure-cli
    
RUN az extension add -y -s https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-release/Preview/E7501C02541B433786111FE8E140CAA1/azure_cli_ml-0.1.65-py2.py3-none-any.whl \
	--pip-extra-index-urls  https://azuremlsdktestpypi.azureedge.net/sdk-release/Preview/E7501C02541B433786111FE8E140CAA1

# Install AzCopy
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/ xenial main" > azure.list &&\
	cp ./azure.list /etc/apt/sources.list.d/ &&\
	apt-key adv --keyserver packages.microsoft.com --recv-keys B02C46DF417A0893 &&\
	apt-get update &&\
	apt-get install -y --no-install-recommends azcopy

COPY Docker/jupyter_notebook_config.py /root/.jupyter/

RUN jupyter nbextension install --py --user azureml.train.widgets && \
	jupyter nbextension enable --py --user azureml.train.widgets

WORKDIR /workspace

CMD /bin/bash

FROM gpubase AS execution
COPY experiment/ /workspace
ENV PYTHONPATH  $PYTHONPATH:/workspace/src
WORKDIR /workspace
CMD /bin/bash