name: ksalt
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - numpy
  - pyyaml
  - scipy
  - pandas
  - ipykernel
  - scikit-learn
  - pillow
  - matplotlib
  - seaborn
  - scikit-image
  - pytorch
  - pip:
    - torchvision
    - tqdm
    - gitpython
    - papermill
    - fire
    - tensorboardX
    - azure
    - azureml-sdk[notebooks, automl]==0.1.68
    