name: ksalt
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - numpy
  - pyyaml
  - scipy
  - ipython
  - pandas
  - jupyter
  - ipykernel
  - scikit-learn
  - pillow
  - matplotlib
  - seaborn
  - scikit-image
  - pytorch
  - pip:
    - torchvision
    - tqdm
    - gitpython
    - kaggle 
    - papermill
    - fire
    - pydot
    - "--editable=git+https://github.com/szagoruyko/pytorchviz#egg=pytorchviz"
    - tensorboard